package DSMS_CORBA;


/**
* DSMS_CORBA/DSMS.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Distributed_Staff_Management_System.idl
* Thursday, June 16, 2016 3:42:09 AM EDT
*/

public interface DSMS extends DSMSOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DSMS
